server:
  port: 80


mybatis:
  config-location: classpath:/mybatis.xml
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: me.fengkmm.seckill.entity


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?useSSL=false
    username: root
    password: 2218890669
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 1

logging:
  level.me.fengkmm.spike.mapper: debug
#  level.org.springframework.boot.autoconfigure: debug
#  level.org.springframework.web.servlet: debug

#debug: true

